name: todo
description: Learning project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
